name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Idris using nix
        run: nix-env -f "<nixpkgs>" -iA idris

      - name: Build project using Idris
        run: idris --build act.ipkg
