name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        
      - name: install idris
        run: |
          export NIXPKGS_ALLOW_BROKEN=1
          nix-env --impure -f "<nixpkgs>" -iA idris

      - name: Build project using Idris
        run: idris --build act.ipkg
